name: EcoTracker Bridge
version: "1.0.9"
slug: ecotracker_bridge
description: >-
  Liest einen physischen everHome EcoTracker und gibt ihn als virtuellen
  EcoTracker aus (HTTP Port 80 + mDNS _everhome._tcp) für Growatt NOAH.
url: https://github.com/5snowflake5/ecotracker-bridge
arch:
  - aarch64
  - amd64
init: false
startup: services
boot: auto
host_network: true
options:
  source_url: "http://192.168.55.140"
  poll_seconds: 0
  log_level: info
  port: 80
  mac: "B43A45A1B2C3"
  serial: "293d45273261"
  productid: "1137"
  announce_ip: ""
schema:
  source_url: str
  poll_seconds: int(0,60)
  log_level: list(info|debug)
  port: port
  mac: str
  serial: str
  productid: str
  announce_ip: str
